added game screen layout
hatdogteam/red-flags-clone pull request #17
Opened 2021-03-13 12:44 UTC by ian-tabs

game screen layout only, not all game room properties handled yet

2021-05-02 04:02 UTC, ptsimon requested changes

2021-05-02 04:02 UTC, ptsimon commented on package.json
> +  }
@ian-tabs  San galing to? Need ba? cc @jacintojosh @jayehernandez

2021-05-02 04:02 UTC, ptsimon commented on frontend/src/App.tsx
> +);
@ian-tabs `App.tsx` must be a clean slate. Please remove all tests. cc @jacintojosh @jayehernandez

2021-05-03 05:52 UTC, jayehernandez commented on frontend/src/App.tsx
> +);
Agree!

2021-05-03 06:09 UTC, jayehernandez requested changes

2021-05-03 06:09 UTC, jayehernandez commented on frontend/src/screens/GameScreen.tsx
> +        <Flex justifyContent="center"><Button background="#319795" size="sm" height="48px" width="122px" radius="8px" fontWeight="700">Proceed</Button></Flex>
Use the variant property for this (this will also add border radius). Also as much as possible we don't want to specify height or width for this. You can change it to:
```
<Button size="sm" variant="primary">
  Proceed
</Button>
```

2021-05-03 06:09 UTC, jayehernandez commented on frontend/src/screens/GameScreen.tsx
> +          <Text fontSize="4xl" color="#4FD1C5" fontFamily="Sora">
Use teal.300 :)

2021-05-03 06:09 UTC, jayehernandez commented on frontend/src/screens/GameScreen.tsx
> +        <Flex justifyContent="center" position="fixed" bottom="0" w="100%" background="#0E151C"><Button background="#319795" size="sm" height="48px" width="122px" radius="8px" fontWeight="700">Next</
Same comment for button here, and make flex background darkGray.800 or 900 (not sure)

2021-05-03 06:09 UTC, jayehernandez commented on frontend/src/screens/GameScreen.tsx
> +  // return (
Remove comments

2021-05-03 06:09 UTC, jayehernandez commented on package.json
> +  }
Hmm since wala siya sa frontend folder, di ata need nito. Paremove na lang :)

2021-05-03 06:09 UTC, jayehernandez commented on frontend/src/screens/GameScreen.tsx
> +        <Flex justifyContent="center" padding="15px 5% 0">
Let's be consistent with padding and margin siguro hmm either px values or yung nasa [Chaka na theme ](https://chakra-ui.com/docs/theming/theme#spacing) (recommended way)

2021-05-03 12:31 UTC, ian-tabs commented on frontend/src/components/navigation/MobileSidebar.tsx
> +
ok po

2021-05-03 12:31 UTC, ian-tabs commented on package.json
> +  }
huehuhue ok

2021-05-03 12:32 UTC, ian-tabs commented on frontend/src/screens/GameScreen.tsx
> +      <Flex justifyContent="center" flexDirection="column" width="100%">
thankyou for your review i will work on it

2021-05-08 09:22 UTC, jacintojosh commented on .vscode/settings.json
> +  // "eslint.run": "onSave",
Uncomment.

2021-05-08 13:27 UTC, ian-tabs commented on frontend/src/components/navigation/MobileSidebar.tsx
>    const players: Player[] = [
di pa pwede remove mga sample data within components as of now po

2021-05-08 13:31 UTC, jayehernandez commented on frontend/src/components/navigation/MobileSidebar.tsx
>    const players: Player[] = [
Okay po noted thank you

2021-05-09 12:05 UTC, ian-tabs commented on frontend/src/screens/GameScreen.tsx
> +          <Text fontSize="4xl" color="#4FD1C5" fontFamily="Sora">
sorry po :(

2021-05-09 13:24 UTC, hatdogteam approved these changes

2021-05-09 13:36 UTC, jacintojosh commented on frontend/src/App.tsx
> +        path="/gamer"
Change path to `/game/:gameId`

2021-05-09 13:41 UTC, ptsimon approved these changes
Thanks for working on this! LGTM, just resolve the merge conflicts.

2021-05-09 13:58 UTC, jacintojosh commented on frontend/src/App.tsx
> +        path="/game /:gameId"
Remove the space. Should be `/game/;gameId`

2021-05-09 14:21 UTC, jayehernandez approved these changes
Ty! LGTM after Joshua's last comment :)

2021-05-13 15:32 UTC, jacintojosh commented
Resolve conflicts, then you can merge!

2021-05-13 15:33 UTC, jacintojosh approved these changes

2021-05-15 04:39 UTC, merged